import { MI } from './mi'
import { Outs_Stat } from './outs_stat'
import { Performance_Data } from './performance_data'
import { Tx_Pool_Performance_Data } from './tx_pool_performance_data'

export interface GetInfo {
	alias_count: number,
	alt_blocks_count: number,
	block_reward: number,
	current_blocks_median: number,
	current_max_allowed_block_size: number,
	current_network_hashrate_350: number,
	current_network_hashrate_50: number,
	daemon_network_state: number,
	default_fee: number,
	expiration_median_timestamp: number,
	grey_peerlist_size: number,
	height: number,
	incoming_connections_count: number,
	last_block_hash: string,
	last_block_size: number,
	last_block_timestamp: number,
	last_block_total_reward: number,
	last_pos_timestamp: number,
	last_pow_timestamp: number,
	max_net_seen_height: number,
    mi: MI,
	minimum_fee: number,
	net_time_delta_median: number,
	offers_count: number,
	outgoing_connections_count: number,
    outs_stat: Outs_Stat,
    performance_data: Performance_Data,
	pos_allowed: boolean,
	pos_block_ts_shift_vs_actual: number,
	pos_diff_total_coins_rate: number,
	pos_difficulty: string,
	pos_sequence_factor: number,
	pow_difficulty: number,
	pow_sequence_factor: number,
	seconds_for_10_blocks: number,
	seconds_for_30_blocks: number,
	status: string,
	synchronization_start_height: number,
	synchronized_connections_count: number,
	total_coins: string,
	transactions_cnt_per_day: number,
	transactions_volume_per_day: number,
	tx_count: number,
	tx_count_in_last_block: number,
	tx_pool_performance_data: Tx_Pool_Performance_Data,
	tx_pool_size: number,
	white_peerlist_size: number,
	lastBlock: number
}